name: M5_python_package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Test
      run: |
        pytest

